name: Run Python Script

on:
  push:
    branches:
      - main  # Le script se déclenche à chaque push sur la branche main
  schedule:
    - cron: '0 8 * * *'  # Le script se déclenche tous les jours à 8h00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        URL_BAILLEUR_1: ${{ vars.URL_BAILLEUR_1 }}
        URL_BAILLEUR_2: ${{ vars.URL_BAILLEUR_2 }}
        URL_BAILLEUR_4: ${{ vars.URL_BAILLEUR_4 }}
      run: |
        python main.py
    
    # - name: Send mail
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     connection_url: ${{secrets.MAIL_CONNECTION}}
    #     # Required mail server address if not connection_url:
    #     server_address: smtp.gmail.com
    #     # Server port, default 25:
    #     server_port: 465
    #     # Optional whether this connection use TLS (default is true if server_port is 465)
    #     secure: true
    #     # Optional (recommended) mail server username:
    #     username: ${{secrets.MAIL_USERNAME}}
    #     # Optional (recommended) mail server password:
    #     password: ${{secrets.MAIL_PASSWORD}}
    #     # Required mail subject:
    #     subject: Github Actions job result
    #     # Required recipients' addresses:
    #     to: obiwan@example.com,yoda@example.com
    #     # Required sender full name (address can be skipped):
    #     from: Luke Skywalker # <user@example.com>
